## 練習時間
資料的操作有很多，接下來的馬拉松中我們會介紹常被使用到的操作，參加者不妨先自行想像一下，第一次看到資料，我們一般會想知道什麼訊息？

#### Ex: 如何知道資料的 row 數以及 column 數、有什麼欄位、多少欄位、如何截取部分的資料等等

有了對資料的好奇之後，我們又怎麼通過程式碼來達成我們的目的呢？

#### 可參考該[基礎教材](https://bookdata.readthedocs.io/en/latest/base/01_pandas.html#DataFrame-%E5%85%A5%E9%97%A8)或自行 google

In [11]:
import os
import numpy as np
import pandas as pd

In [19]:
# 設定 data_pathC:\Users\ethan.wu\Documents\GitHub\2nd-ML100Days\data
#dir_data = 'c:/Users/ethan.wu/Documents/GitHub/2nd-ML100Days/data/'
dir_data = './data/'

In [20]:
f_app = os.path.join(dir_data, 'application_train.csv')
print('Path of read in data: %s' % (f_app))
app_train = pd.read_csv(f_app)

Path of read in data: ./data/application_train.csv

### 如果沒有想法，可以先嘗試找出剛剛例子中提到的問題的答案
#### 資料的 row 數以及 column 數

In [35]:
app_train.shape

(307511, 122)

#### 列出所有欄位

In [36]:
app_train.columns

Index(['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY',
       ...
       'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
       'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype='object', length=122)

#### 截取部分資料

In [55]:
app_train[:][55:77]

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
55,100063,0,Cash loans,F,N,Y,0,180000.0,837427.5,45558.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,4.0
56,100064,0,Cash loans,F,N,N,0,67500.0,298728.0,15381.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
57,100068,0,Revolving loans,M,N,Y,0,81000.0,247500.0,12375.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
58,100069,0,Cash loans,M,Y,Y,1,360000.0,640458.0,27265.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,3.0
59,100070,0,Cash loans,M,Y,Y,0,540000.0,1227901.5,46899.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
60,100071,0,Cash loans,F,N,Y,0,180000.0,1663987.5,86989.5,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0
61,100072,0,Cash loans,M,N,N,0,180000.0,1080000.0,44118.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
62,100073,0,Cash loans,M,Y,Y,0,324000.0,1130760.0,40189.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
63,100075,0,Cash loans,F,N,N,0,112500.0,95940.0,10462.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
64,100076,0,Cash loans,M,Y,N,0,180000.0,315000.0,9679.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
65,100077,0,Cash loans,M,N,Y,0,180000.0,1256400.0,40657.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,8.0
66,100078,0,Cash loans,F,Y,Y,0,180000.0,1035000.0,43983.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
67,100079,0,Revolving loans,M,N,Y,0,225000.0,270000.0,13500.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
68,100080,0,Revolving loans,F,N,N,1,157500.0,450000.0,22500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
69,100081,0,Cash loans,M,Y,N,0,180000.0,450000.0,21109.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
70,100082,0,Cash loans,M,N,N,2,180000.0,450000.0,21109.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0
71,100083,0,Cash loans,M,Y,Y,0,103500.0,573628.5,24435.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
72,100084,0,Cash loans,M,N,Y,2,225000.0,495351.0,26140.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
73,100085,0,Cash loans,M,N,Y,1,157500.0,755190.0,28894.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
74,100086,0,Cash loans,F,N,Y,1,135000.0,675000.0,21775.5,...,0,0,0,0,0.0,0.0,0.0,1.0,4.0,2.0
75,100087,0,Cash loans,F,N,Y,1,202500.0,1288350.0,37800.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
76,100088,0,Revolving loans,F,N,N,0,112500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0

#### 還有各種數之不盡的資料操作，重點還是取決於實務中遇到的狀況和你想問的問題，在馬拉松中我們也會陸續提到更多例子

In [57]:
app_train[:][55:77].fillna(0)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
55,100063,0,Cash loans,F,N,Y,0,180000.0,837427.5,45558.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,4.0
56,100064,0,Cash loans,F,N,N,0,67500.0,298728.0,15381.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
57,100068,0,Revolving loans,M,N,Y,0,81000.0,247500.0,12375.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
58,100069,0,Cash loans,M,Y,Y,1,360000.0,640458.0,27265.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,3.0
59,100070,0,Cash loans,M,Y,Y,0,540000.0,1227901.5,46899.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
60,100071,0,Cash loans,F,N,Y,0,180000.0,1663987.5,86989.5,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0
61,100072,0,Cash loans,M,N,N,0,180000.0,1080000.0,44118.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
62,100073,0,Cash loans,M,Y,Y,0,324000.0,1130760.0,40189.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
63,100075,0,Cash loans,F,N,N,0,112500.0,95940.0,10462.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
64,100076,0,Cash loans,M,Y,N,0,180000.0,315000.0,9679.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
65,100077,0,Cash loans,M,N,Y,0,180000.0,1256400.0,40657.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,8.0
66,100078,0,Cash loans,F,Y,Y,0,180000.0,1035000.0,43983.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
67,100079,0,Revolving loans,M,N,Y,0,225000.0,270000.0,13500.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
68,100080,0,Revolving loans,F,N,N,1,157500.0,450000.0,22500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
69,100081,0,Cash loans,M,Y,N,0,180000.0,450000.0,21109.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
70,100082,0,Cash loans,M,N,N,2,180000.0,450000.0,21109.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0
71,100083,0,Cash loans,M,Y,Y,0,103500.0,573628.5,24435.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
72,100084,0,Cash loans,M,N,Y,2,225000.0,495351.0,26140.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
73,100085,0,Cash loans,M,N,Y,1,157500.0,755190.0,28894.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
74,100086,0,Cash loans,F,N,Y,1,135000.0,675000.0,21775.5,...,0,0,0,0,0.0,0.0,0.0,1.0,4.0,2.0
75,100087,0,Cash loans,F,N,Y,1,202500.0,1288350.0,37800.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
76,100088,0,Revolving loans,F,N,N,0,112500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0